//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWAuthorizationServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public AccessToken()
        {
            this.ThirdPartyTokens = new HashSet<ThirdPartyToken>();
        }
    
        public string access_token { get; set; }
        public int expire_to { get; set; }
        public string client_id { get; set; }
        public string refresh_token { get; set; }
        public string user_id { get; set; }
        public int access_token_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ThirdPartyToken> ThirdPartyTokens { get; set; }
        public virtual User User { get; set; }
    }
}
