//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWAuthorizationServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MWOAuthDBEntities : DbContext
    {
        public MWOAuthDBEntities()
            : base("name=MWOAuthDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessToken> AccessToken { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<ThirdPartyToken> ThirdPartyToken { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<ChangePasswordToken> ChangePasswordTokenSet { get; set; }
    }
}
