//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWAuthorizationServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.AccessTokens = new HashSet<AccessToken>();
        }
    
        public string client_id { get; set; }
        public string client_seret { get; set; }
        public string scope { get; set; }
    
        public virtual ICollection<AccessToken> AccessTokens { get; set; }
    }
}
