//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWAuthorizationServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MWOAuthDBContainer : DbContext
    {
        public MWOAuthDBContainer()
            : base("name=MWOAuthDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessToken> AccessTokens { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<ThirdPartyToken> ThirdPartyTokens { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
